import {
    objectSize,
    stringSize,
    last,
    copyBy,
    timer,
    interval,
    validID,
    isNumber,
    isPromise,
    uniq,
    isFunction,
    isObject,
    isArray,
    isString,
    isFalsy,
    copy,
    delay,
    someKeyMatch,
    exactKeyMatch,
    head,
    trueVal,
    trueValDeep,
    trueProp,
    typeCheck,  
    isEmpty,
    isError,
    validDate,
    isClass,
    hasPrototype,
    isInstance,
    hasProto,
    log,
    warn,
    debug,
    attention,
    alert,
    selectiveArray,
    resolver,
    onerror,
    stack,
    chunks,
    errorTrace,
    flattenDeep,
    flatten,
    dupes,
    loop,
    disableLogging,
    resetLogging,
    error,
    loggerSetting,
    isTrue,
    isFalse,
    isUndefined,
    isNull,
    isBoolean,
    copyDeep,
    sq,
    cancelPromise,
    shuffle, 
    isQPromise,
    uniqBy,
    arrayWith,
    exFromArray,
    pickFromArray,
    dispatcher,
    withHoc
    /** 
     * `esm` > (default) and node support for with esnext,  // node -r esm examples 
     * `umd` > universal module/es2015 
    */
} from '../src'

log({ isArray: isArray([1], () => false) })
log({ validDate: validDate(new Date(), () => false) })
log({ head: head([1, 2], () => true) })
log({ last: last([1, 2], () => false) })
log({ isObject: isObject({ 1: 1 }, () => false) })
log({ isString: isString('1', () => false) })
